apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotmple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: kotmple:1.0.0
          name: kotmple
          ports:
            - containerPort: 80
